# Generated by Django 5.0.6 on 2024-05-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_api', '0002_fromorder_ingredients_kebabapiroles_kebabingredients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FromOrder',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='KebabApiRoles',
        ),
        migrations.DeleteModel(
            name='KebabIngredients',
        ),
        migrations.DeleteModel(
            name='Kebabs',
        ),
        migrations.DeleteModel(
            name='KebabsOrdered',
        ),
        migrations.DeleteModel(
            name='OrderFeedbacks',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={},
        ),
    ]
