# Generated by Django 5.0.6 on 2024-05-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_api', '0004_fromorder_ingredients_kebabingredients_kebabs_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
    ]
