# Generated by Django 5.0.6 on 2024-05-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_api', '0005_alter_roles_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role_id',
            new_name='role',
        ),
    ]
