# Generated by Django 5.0.6 on 2024-05-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_api', '0007_rename_role_users_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role_id',
            new_name='role',
        ),
    ]
